name: Daily Automated Tests

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC every day
  workflow_dispatch:  # Allow manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests with coverage
        run: npm run test:coverage
        
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
          
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Start app in background
        run: npm run dev &
        env:
          VITE_API_URL: 'https://docuaid-backend-production.up.railway.app'
          
      - name: Wait for app to start
        run: sleep 30
        
      - name: Run endpoint tests
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5173)
          echo "Status code: $STATUS_CODE"
          if [[ "$STATUS_CODE" -ne 200 ]]; then
            echo "App is not running correctly"
            exit 1
          else
            echo "App is running correctly!"
          fi
          
      - name: Check production site
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://docuaid.online)
          echo "Status code: $STATUS_CODE"
          if [[ "$STATUS_CODE" -ne 200 ]]; then
            echo "Production site is not responding with 200 OK"
            exit 1
          else
            echo "Production site is up and running!"
          fi
          
      - name: Send notification on failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: "Automated Tests Failed"
          SLACK_MESSAGE: "The daily automated tests for DocuAid failed. Please investigate."
          SLACK_COLOR: danger
        continue-on-error: true 